name: A workflow for my Hello World file
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Burak"